// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJQMCOo38tie3sEL070kzVsVs5_pOS0GQ',
    appId: '1:744954469846:web:57af1b7da5c8ad55aa1877',
    messagingSenderId: '744954469846',
    projectId: 'ulearning-app-89121',
    authDomain: 'ulearning-app-89121.firebaseapp.com',
    storageBucket: 'ulearning-app-89121.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYN1fUvyC-wjJ3RD7j4rXJriJADPz1ykI',
    appId: '1:744954469846:android:6943fd1eb86d88adaa1877',
    messagingSenderId: '744954469846',
    projectId: 'ulearning-app-89121',
    storageBucket: 'ulearning-app-89121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDitYdm4SiVw-LHjEVtHWSLfOVjI3wZmaI',
    appId: '1:744954469846:ios:84894dfa844a0c95aa1877',
    messagingSenderId: '744954469846',
    projectId: 'ulearning-app-89121',
    storageBucket: 'ulearning-app-89121.appspot.com',
    androidClientId: '744954469846-k8ooman721p7ol5iqpthju8h8769c8ua.apps.googleusercontent.com',
    iosClientId: '744954469846-lhr9ptg6p85k433s0cmrves7lvvv19u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDitYdm4SiVw-LHjEVtHWSLfOVjI3wZmaI',
    appId: '1:744954469846:ios:a95cf273e368582faa1877',
    messagingSenderId: '744954469846',
    projectId: 'ulearning-app-89121',
    storageBucket: 'ulearning-app-89121.appspot.com',
    androidClientId: '744954469846-k8ooman721p7ol5iqpthju8h8769c8ua.apps.googleusercontent.com',
    iosClientId: '744954469846-3v21sc9gdumh4f1dj5uc6l0t6p5h3fpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulearningApp.RunnerTests',
  );
}
